### PR TITLE
Release/4.3.1

### PR DESCRIPTION
**Pull request by ataheridezfouli-groq**

### CODE REVIEW

**Comment by ataheridezfouli-groq** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ataheridezfouli-groq** [comment]
recheck

**Comment by ataheridezfouli-groq** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ataheridezfouli-groq** [comment]
recheck

**Comment by czawistowski-groq** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Pull request merged**
